# ./.tmuxinator.yml
<% require 'uri' %>

name: adquick
root: <%= ENV['ADQUICK_DIR'] %>

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

windows:
  - adquick:
      root: <%= ENV['ADQUICK_DIR'] %>/adquick
      layout: tiled
      panes:
        - eval "$(nodenv init -)"; echo bundle exec guard -i -d -w . -n f -P rspec; spring server
        - eval "$(nodenv init -)"; ssh-add
  - pgcenter:
      <% replica_url = ::URI.parse(`grep ^REPLICA_DATABASE_URL #{File.join(*[ENV['ADQUICK_DIR'], 'adquick', 'heroku_env.conf'].join('/'))}`.split(/ +/)[1].chomp)  %>
      <% main_url = ::URI.parse(`grep ^DATABASE_URL #{File.join(*[ENV['ADQUICK_DIR'], 'adquick', 'heroku_env.conf'].join('/'))}`.split(/ +/)[1].chomp)  %>
      <% alloy_url = ::URI.parse(`grep ^ALLOY_DATABASE_URL #{File.join(*[ENV['ADQUICK_DIR'], 'adquick', 'heroku_env.conf'].join('/'))}`.split(/ +/)[1].chomp)  %>
      <% pooler_url = ::URI.parse(`grep ^DATABASE_CONNECTION_POOL_URL #{File.join(*[ENV['ADQUICK_DIR'], 'adquick', 'heroku_env.conf'].join('/'))}`.split(/ +/)[1].chomp)  %>
      root: <%= ENV['ADQUICK_DIR'] %>/adquick
      layout: tiled
      panes:
        - pgcenter top -h <%= main_url.host %> -U <%= main_url.user %> -d <%= main_url.path[1..-1] %>
        - pgcenter top -h <%= replica_url.host %> -U <%= replica_url.user %> -d <%= replica_url.path[1..-1] %>
        - pgcenter top -h <%= alloy_url.host %> -U <%= alloy_url.user %> -d <%= alloy_url.path[1..-1] %>
        - pgcenter top -h <%= pooler_url.host %> -U <%= pooler_url.user %> -d <%= pooler_url.path[1..-1] %> -p <%= pooler_url.port %>
  - servers:
      root: <%= ENV['ADQUICK_DIR'] %>/adquick
      layout: tiled
      # Synchronize all panes of this window, can be enabled before or after the pane commands run.
      # 'before' represents legacy functionality and will be deprecated in a future release, in favour of 'after'
      # synchronize: after
      panes:
        - redis-server
        - echo bundle exec rails s -b "ssl://localhost.adquick:3002?key=../adquick_analytics/.certs/localhost.adquick-key.pem&cert=../adquick_analytics/.certs/localhost.adquick.crt&verify_mode=none"
        - toxiproxy-server --config ~/.config/toxiproxy.json
        - sleep 5; toxiproxy-cli l
        - echo yarn start:classic
        - eval "$(nodenv init -)"; echo yarn start
        # this does:
        # - anycable-go --host=localhost --port=3334
        # - bundle exec anycable --debug
  - top:
      panes:
        - htop
        - btop
  - llm:
      panes:
        - nvtop
        - podman run --replace -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama && podman exec -it ollama ollama run deepseek-r1
  - mitmproxy-rails:
      root: <%= ENV['ADQUICK_DIR'] %>/adquick
      layout: tiled
      panes:
        - mitmproxy --mode reverse:http://localhost:3000@localhost:8081
  - mitmproxy-outbound:
      root: <%= ENV['ADQUICK_DIR'] %>/adquick
      layout: tiled
      panes:
        - mitmproxy -p 8090
  - staging-pgcenter:
      <% staging_replica_url = ::URI.parse(`grep ^REPLICA_DATABASE_URL #{File.join(*[ENV['ADQUICK_DIR'], 'adquick', 'heroku_env_adtest.conf'].join('/'))}`.split(/ +/)[1].chomp)  %>
      <% staging_main_url = ::URI.parse(`grep ^DATABASE_URL #{File.join(*[ENV['ADQUICK_DIR'], 'adquick', 'heroku_env_adtest.conf'].join('/'))}`.split(/ +/)[1].chomp)  %>
      root: <%= ENV['ADQUICK_DIR'] %>/adquick
      layout: tiled
      panes:
        - pgcenter top -h <%= staging_main_url.host %> -U <%= staging_main_url.user %> -d <%= staging_main_url.path[1..-1] %>
        - pgcenter top -h <%= staging_replica_url.host %> -U <%= staging_replica_url.user %> -d <%= staging_replica_url.path[1..-1] %>
  - emacs-cli:
      root: <%= ENV['ADQUICK_DIR'] %>/adquick
      layout: tiled
      panes:
        - emacsclient -nw ./
