AllCops:
  DisabledByDefault: true

CustomCops/NoComplexInitializeAssignment:
  Enabled: true
  Methods:
    - initialize
    - perform
  Include:
    - "app/**/*.rb"

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
