inherit_from:
  - config.local.yml

AllCops:
  DisabledByDefault: true

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Style/BlockDelimiters:
  Enabled: true

Naming/MemoizedInstanceVariableName:
  Enabled: true

CustomCops/NoComplexInitializeAssignment:
  Enabled: true
  Methods:
    - initialize
    - perform
  Include:
    - "app/**/*.rb"

CustomCops/NoIvarOutsideEntryMethod:
  Enabled: true
  EntryMethods:
    - initialize
    - perform
  Include:
    - "app/**/*.rb"

CustomCops/RescueRequiresReraise:
  Enabled: true
  RaiseGuard: "TestOnlyBehavior.raise_errors?"
  Include:
    - "app/**/*.rb"

CustomCops/NoInstanceVariableGetSet:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
